var MAX_FILAMENTS = 10;

var SPEED_SCALE = 0.00004;

var FILAMENT_RADIUS = 0.1;

var FRAMES_BETWEEN_EMISSIONS = 50;
var PARTICLE_LIFETIME = FRAMES_BETWEEN_EMISSIONS * MAX_FILAMENTS; //frames between particle respawns

var FILAMENT_GEOMETRY_RADIUS_SCALE = 0.035;